conda install pip
pip install --upgrade pip==24.2
pip install --upgrade numpy==2.1.2
pip install --upgrade anyio==4.6.0
pip install --upgrade argon2-cffi==23.1.0
pip install --upgrade argon2-cffi-bindings==21.2.0
pip install --upgrade arrow==1.3.0
pip install --upgrade asttokens==2.4.1
pip install --upgrade async-lru==2.0.4
pip install --upgrade attrs==24.2.0
pip install --upgrade babel==2.16.0
pip install --upgrade beautifulsoup4==4.12.3
pip install --upgrade bleach==6.1.0
pip install --upgrade certifi==2024.8.30
pip install --upgrade cffi==1.17.1
pip install --upgrade charset-normalizer==3.3.2
pip install --upgrade cloudpickle==3.0.0
pip install --upgrade comm==0.2.2
pip install --upgrade contourpy==1.3.0
pip install --upgrade cycler==0.12.1
pip install --upgrade debugpy==1.8.6
pip install --upgrade decorator==5.1.1
pip install --upgrade defusedxml==0.7.1
pip install --upgrade executing==2.1.0
pip install --upgrade Farama-Notifications==0.0.4
pip install --upgrade fastjsonschema==2.20.0
pip install --upgrade filelock==3.16.1
pip install --upgrade fonttools==4.54.1
pip install --upgrade fqdn==1.5.1
pip install --upgrade fsspec==2024.9.0
pip install --upgrade gymnasium==0.29.1
pip install --upgrade h11==0.14.0
pip install --upgrade httpcore==1.0.6
pip install --upgrade httpx==0.27.2
pip install --upgrade idna==3.10
pip install --upgrade ipykernel==6.29.5
pip install --upgrade ipython==8.28.0
pip install --upgrade ipywidgets==8.1.5
pip install --upgrade isoduration==20.11.0
pip install --upgrade jedi==0.19.1
pip install --upgrade Jinja2==3.1.4
pip install --upgrade json5==0.9.25
pip install --upgrade jsonpointer==3.0.0
pip install --upgrade jsonschema==4.23.0
pip install --upgrade jsonschema-specifications==2023.12.1
pip install --upgrade jupyter==1.1.1
pip install --upgrade jupyter_client==8.6.3
pip install --upgrade jupyter-console==6.6.3
pip install --upgrade jupyter_core==5.7.2
pip install --upgrade jupyter-events==0.10.0
pip install --upgrade jupyter-lsp==2.2.5
pip install --upgrade jupyter_server==2.14.2
pip install --upgrade jupyter_server_terminals==0.5.3
pip install --upgrade jupyterlab==4.2.5
pip install --upgrade jupyterlab_pygments==0.3.0
pip install --upgrade jupyterlab_server==2.27.3
pip install --upgrade jupyterlab_widgets==3.0.13
pip install --upgrade kiwisolver==1.4.7
pip install --upgrade MarkupSafe==3.0.0
pip install --upgrade matplotlib==3.9.2
pip install --upgrade matplotlib-inline==0.1.7
pip install --upgrade mistune==3.0.2
pip install --upgrade mpmath==1.3.0
pip install --upgrade nbclient==0.10.0
pip install --upgrade nbconvert==7.16.4
pip install --upgrade nbformat==5.10.4
pip install --upgrade nest-asyncio==1.6.0
pip install --upgrade networkx==3.3
pip install --upgrade notebook==7.2.2
pip install --upgrade notebook_shim==0.2.4
pip install --upgrade nvidia-cublas-cu12==12.1.3.1
pip install --upgrade nvidia-cuda-cupti-cu12==12.1.105
pip install --upgrade nvidia-cuda-nvrtc-cu12==12.1.105
pip install --upgrade nvidia-cuda-runtime-cu12==12.1.105
pip install --upgrade nvidia-cudnn-cu12==9.1.0.70
pip install --upgrade nvidia-cufft-cu12==11.0.2.54
pip install --upgrade nvidia-curand-cu12==10.3.2.106
pip install --upgrade nvidia-cusolver-cu12==11.4.5.107
pip install --upgrade nvidia-cusparse-cu12==12.1.0.106
pip install --upgrade nvidia-nccl-cu12==2.20.5
pip install --upgrade nvidia-nvjitlink-cu12==12.6.77
pip install --upgrade nvidia-nvtx-cu12==12.1.105
pip install --upgrade overrides==7.7.0
pip install --upgrade packaging==24.1
pip install --upgrade pandas==2.2.3
pip install --upgrade pandocfilters==1.5.1
pip install --upgrade parso==0.8.4
pip install --upgrade pexpect==4.9.0
pip install --upgrade pillow==10.4.0
pip install --upgrade platformdirs==4.3.6
pip install --upgrade prometheus_client==0.21.0
pip install --upgrade prompt_toolkit==3.0.48
pip install --upgrade psutil==6.0.0
pip install --upgrade ptyprocess==0.7.0
pip install --upgrade pure_eval==0.2.3
pip install --upgrade pycparser==2.22
pip install --upgrade Pygments==2.18.0
pip install --upgrade pyparsing==3.1.4
pip install --upgrade python-dateutil==2.9.0.post0
pip install --upgrade python-json-logger==2.0.7
pip install --upgrade pytz==2024.2
pip install --upgrade PyYAML==6.0.2
pip install --upgrade pyzmq==26.2.0
pip install --upgrade referencing==0.35.1
pip install --upgrade requests==2.32.3
pip install --upgrade rfc3339-validator==0.1.4
pip install --upgrade rfc3986-validator==0.1.1
pip install --upgrade rpds-py==0.20.0
pip install --upgrade seaborn==0.13.2
pip install --upgrade Send2Trash==1.8.3
pip install --upgrade setuptools==75.1.0
pip install --upgrade six==1.16.0
pip install --upgrade sniffio==1.3.1
pip install --upgrade soupsieve==2.6
pip install --upgrade stable_baselines3==2.3.2
pip install --upgrade stack-data==0.6.3
pip install --upgrade sympy==1.13.3
pip install --upgrade terminado==0.18.1
pip install --upgrade tinycss2==1.3.0
pip install --upgrade torch==2.4.1
pip install --upgrade tornado==6.4.1
pip install --upgrade traitlets==5.14.3
pip install --upgrade triton==3.0.0
pip install --upgrade types-python-dateutil==2.9.0.20241003
pip install --upgrade typing_extensions==4.12.2
pip install --upgrade tzdata==2024.2
pip install --upgrade uri-template==1.3.0
pip install --upgrade urllib3==2.2.3
pip install --upgrade wcwidth==0.2.13
pip install --upgrade webcolors==24.8.0
pip install --upgrade webencodings==0.5.1
pip install --upgrade websocket-client==1.8.0
pip install --upgrade wheel==0.44.0
pip install --upgrade widgetsnbextension==4.0.13
